### ISSUE TITLE
chore: enable lint action 

### ISSUE THREAD

**Issue by aalemayhu** [2anki/server#638]
also decide on the rules to use.

**Comment by Renni771** [comment]
Hey @aalemayhu here's a proposed draft we could use in the eslint config to enforce general type safety, code style and the issues mentioned in issue #554:

(comments won't be added to actual config file)
```json
{
  "env": {
    "es2021": true,
    "node": true
  },
  "extends": [
    "eslint:recommended",
    "plugin:@typescript-eslint/recommended"
  ],
  
  // Ignore the various migrations issues
  "ignorePatterns": [
    "**/migrations/*.js"
  ],
  "parser": "@typescript-eslint/parser",
  "parserOptions": {
    "ecmaVersion": "latest",
    "sourceType": "module"
  },
  "plugins": [
    "@typescript-eslint"
  ],
  "rules": {
    "eqeqeq": [ "error", "always" ],
    "indent": [ "error", 2 ],
    "linebreak-style": [ "error", "unix" ],
    "quotes": [ "error", "double" ],
    "semi": [ "error", "always" ],
    "@typescript-eslint/ban-ts-comment": "off"
  }
}
```

I quickly whipped up this draft trying my best to respect the current code style. The use of `any` as mentioned in #554 can be remedied by defining those basic linter rules. Currently this config raises warnings whenever `any` is used. I took a look and there are a few cases where the use of `any` may be justified e.g in `lib/parser/Settings.ts`:

```typescript
   ...
line 45:  constructor(input: any) {
    this.deckName = input.deckName;
   ...
```

Here it may be favourable to use a `Record<string, any>`. The edge cases where more specific attention is need for typing could be discussed in another issue, but the basic scaffolding would at least be taken care of here.

**Comment by aalemayhu** [comment]
I did not see this comment before now and actually preparing a pull request to enable eslint. I don't mind changing the code to new rules so it does not have to match the current code style but instead be consistent moving forward.

I will add you as reviewer for that one, note I have several other changes related to Sonarcloud but ideally the pull requests should focus on one issue at a time and not do several things. So it's easier for reviewer to look at one issue at a time.
