### ISSUE TITLE
Can't create notion page to anki 

### ISSUE THREAD

**Issue by mathias7230** [2anki/server#793]
Hello, I can't create a notion page to anki :
I took screenshot : 
![image](https://user-images.githubusercontent.com/112640033/187940379-990dd2c9-62d7-4379-9e18-8810adcb44db.png)
![image](https://user-images.githubusercontent.com/112640033/187940692-90584de7-ffd1-4e71-b0ee-8d181a703ee0.png)
![image](https://user-images.githubusercontent.com/112640033/187940931-5abfac55-256f-49fc-882a-8e8bb063965f.png)

Can you help me please ?

**Comment by aalemayhu** [comment]
You were using toggle headings which was not supported in the HTML upload until recently. Please try again
